### ISSUE TITLE
Link text to big on mainpage

### ISSUE THREAD

**Issue by eddyahlqvist** [timahlqvist/lioar.se#2]
The link 'Facebook sidan' doesn't fit. It goes outside it's 'box' and looks bad. Perhaps it's a good idea to change the name or the size.
![namnlos](https://cloud.githubusercontent.com/assets/25877725/23276596/340254f0-fa0b-11e6-8056-32263d860c58.png)

**Comment by timahlqvist** [comment]
Thanks! I will fix it now. And I will also fix some links that not work.

**Comment by eddyahlqvist** [comment]
Looks great now. Cheers!
